server:
  port: 7900
spring:
  application:
    name: eureka
eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka1:7900/eureka/,http://eureka2:7901/eureka/,http://eureka3:7902/eureka/
      defaultZone: http://eureka1:7900/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    renewal-percent-threshold: 0.85 #自我保护阈值
    eviction-interval-timer-in-ms: 10000 #间隔多少时间检测服务健康
    use-read-only-response-cache: false #关闭从readOnly读取注册表
    response-cache-update-interval-ms: 10000 #二级缓存同步到三级缓存时间 readWriteCacheMap => readOnlyCacheMap
---
spring:
  profiles: eureka1
eureka:
  instance:
    hostname: eureka1
server:
  port: 7900
---
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
server:
  port: 7901
---
spring:
  profiles: eureka3
eureka:
  instance:
    hostname: eureka3
server:
  port: 7902