server:
  port: 8080
spring:
  application:
    name: api-passenger
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:7900/eureka/,http://eureka2:7901/eureka/,http://eureka3:7902/eureka/